version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mini_market
    ports:
      - "5432:5432"
    volumes:
      - ./microservices/cart-service/init.sql:/docker-entrypoint-initdb.d/cart-service_init.sql
      - ./microservices/review-service/init.sql:/docker-entrypoint-initdb.d/review-service_init.sql
      - ./microservices/analytics-service/init.sql:/docker-entrypoint-initdb.d/analytics-service_init.sql

  user-service:
    build: ./microservices/user-service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=postgresql://user:password@postgres:5432/mini_market
      - JWT_SECRET_KEY=super-secret
    depends_on:
      - postgres

  product-service:
    build: ./microservices/product-service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URI=postgresql://user:password@postgres:5432/mini_market?sslmode=disable
    depends_on:
      - postgres

  inventory-service:
    build: ./microservices/inventory-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URI=postgresql://user:password@postgres:5432/mini_market
    depends_on:
      - postgres

  order-service:
    build: ./microservices/order-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URI=postgresql://user:password@postgres:5432/mini_market?sslmode=disable
    depends_on:
      - postgres

  payment-service:
    build: ./microservices/payment-service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mini_market
    depends_on:
      - postgres

  notification-service:
    build: ./microservices/notification-service
    ports:
      - "8083:8080"
    environment:
      - PORT=8080

  cart-service:
    build: ./microservices/cart-service
    ports:
      - "5005:5000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mini_market
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - postgres

  review-service:
    build: ./microservices/review-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  analytics-service:
    build: ./microservices/analytics-service
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mini_market
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "5004:5004"
    depends_on:
      - postgres
